sudo: required

language: go

services:
- docker

env:
- PROJECT_ID="mysocialapp" PROJECT_NAME="k8s-dns-updater" APP_VERSION="$TRAVIS_TAG" K8S_VERSION=1.8 NUM_NODES=6 SKIP_SNAPSHOT=y PATH="$HOME/.kubeadm-dind-cluster:/tmp/linux-amd64:$PATH"

install:
- tests/k8s-euft/bootstrap_k8s.sh

script:
- make build

after_success:
- bats -t tests/boot/start.bats
- make clean

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

after_deploy:
- test $(curl -s https://quay.io/api/v1/repository/${PROJECT_ID}/${PROJECT_NAME}/tag/ | jq ".tags[] | select(.name == \"${APP_VERSION}\") | select(.end_ts == null) | .name" | wc -l) -eq 0 || echo "Container tag ${APP_VERSION} already exist, cancelling push to avoid override"
- docker build -t quay.io/${PROJECT_ID}/${PROJECT_NAME}:${APP_VERSION} .
- docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
- docker push quay.io/${PROJECT_ID}/${PROJECT_NAME}:${APP_VERSION}
