{{ if .Values.KduRbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubernetes.name" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kubernetes.name" . }}
rules:
- apiGroups: [""]
  resources: ["nodes", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kubernetes.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubernetes.name" . }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ template "kubernetes.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}